services:
  - type: web
    name: yt-clean-proxy
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: COOKIES_PATH
        value: /app/cookies.txt
      - key: BASE_URL
        value: ""
